title: すくライブラリ
description: descriptionはない
email: 0214sh7@gmail.com
baseurl: "/library"
url: "https://github.com/0214sh7"
twitter_username: 0214sh7
github_username:  0214sh7



# Build settings
markdown: kramdown
theme: minima
timezone: Asia/Tokyo
plugins:
  - jekyll-feed

kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts: 
    block:
      #line_numbers: true
    #default_lang: cpp

permalink: /:categories/:short_year-:month-:day/:title